# Generated by Django 3.2 on 2021-12-05 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='new',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=200, null=True)),
                ('weight', models.FloatField(max_length=50, null=True)),
                ('height', models.FloatField(max_length=20, null=True)),
                ('age', models.IntegerField(null=True)),
                ('gender1', models.CharField(blank=True, choices=[(None, 'Gender'), ('Male', 'Male'), ('Female', 'Female'), ('Custom', 'Custom'), ('Prefer Not To Say', 'Prefer Not To Say')], max_length=50, verbose_name='gender')),
            ],
        ),
    ]
