# Generated by Django 3.2 on 2021-12-05 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='diet',
            field=models.CharField(blank=True, choices=[(None, 'diet'), ('balanced', 'Balanced'), ('high-protein', 'High Protein'), ('high-fiber', 'High Fiber'), ('low-fat', 'Low Fat')], max_length=50, verbose_name='diet'),
        ),
    ]
