# Generated by Django 3.2 on 2021-12-05 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_new_diet'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='disorder',
            field=models.CharField(blank=True, choices=[(None, 'Disorder'), ('Binge-eating', 'Binge-eating'), ('Anorexia-nervosa', 'Anorexia nervosa')], max_length=50, verbose_name='diet'),
        ),
        migrations.AlterField(
            model_name='new',
            name='diet',
            field=models.CharField(blank=True, choices=[(None, 'diet'), ('vegetarian', 'Vegetarian'), ('vegan', 'Vegan'), ('gluten-free', 'Gluten free'), ('alcohol-free', 'Alcohol Free')], max_length=50, verbose_name='diet'),
        ),
        migrations.AlterField(
            model_name='new',
            name='gender1',
            field=models.CharField(blank=True, choices=[(None, 'Gender'), ('Male', 'Male'), ('Female', 'Female')], max_length=50, verbose_name='gender'),
        ),
    ]
